[package]
name = "collect-orchestrator"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
parquet.workspace = true
collect-core = { path = "../collect-core" }
ais-parse = { path = "../ais-parse" }
aisstream-parse = { path = "../aisstream-parse" }
axum.workspace = true
sqlx.workspace = true
urlencoding.workspace = true
rand.workspace = true
iceberg.workspace = true
tempfile.workspace = true
toml.workspace = true
simd-json = "0.14"
reqwest.workspace = true
